### ISSUE TITLE
Instance settings dead redirect

### ISSUE THREAD

**Issue by SympathyTea** [PrismLauncher/prismlauncher.org#501] opened 2024-07-15 06:09 UTC
Was told to file this issue under the website repo, but this is in the launcher.

1. Go to instance > settings
2. Press the help button
3. Button leads to [this page](https://prismlauncher.org/wiki/help-pages/Instance-settings) which gives me and others a 404.

Solutions: Make the instance settings help page exist or have it redirect to a different help page section
![instance settings help button](https://github.com/user-attachments/assets/e7dc06b8-ea4b-4851-9fe2-c3d6eaa51bd2)
![404 page not found](https://github.com/user-attachments/assets/1ea76d7d-2222-4083-8a68-5f9e3e189289)

**Comment by Trial97** [comment] 2024-07-16 10:44
Duplicate of: https://github.com/PrismLauncher/prismlauncher.org/issues/97

**Closed by Trial97** 2024-07-16 10:44 UTC
