### ISSUE TITLE
https://prismlauncher.org/wiki/help-pages/Launcher-settings doesn't exist

### ISSUE THREAD

**Issue by theofficialgman** [PrismLauncher/prismlauncher.org#161] opened 2022-11-17 23:53 UTC
this is the link that the launcher takes you when clicking "settings -> help" in the bottom left corner. takes you to a 404 page on prismlauncher website. maybe either create this page, redirect to `https://prismlauncher.org/wiki/help-pages/` or change the launcher so that it points to `https://prismlauncher.org/wiki/help-pages/` instead

**Comment by DioEgizio** [comment] 2022-11-18 08:03
Duplicate of #97

**Closed by DioEgizio** 2022-11-18 08:03 UTC
